---
title: "RTM_AND_DAM_YEAR_GET"
format: html
editor: visual
---

## DAM

```{r}
library(lubridate)
library(tidyverse)
library(readxl)
library(here)
library(zoo)
library(httr)
library(readr)
```

```{r}
dates <- seq.Date(as.Date("2024-01-01"), as.Date("2025-01-01"), by = "month")
dates <- format(dates, "%Y%m%d")

first <- "http://oasis.caiso.com/oasisapi/SingleZip?resultformat=6&queryname=PRC_INTVL_LMP&version=3&startdatetime="
full_RTM_data <- data.frame()

for (date in 1:(length(dates) - 1)) {
  full_url <- paste0(first, dates[date], "T08:00-0000")
  full_url <- paste0(full_url, "&enddatetime=", dates[date + 1], "T07:00-0000&market_run_id=RTM&node=DLAP_PACE_NPM-APND,DLAP_PACW_NPM-APND,DLAP_PGAE-APND,DLAP_SCE-APND,DLAP_SDGE-APND,DLAP_VEA-APND")
  
  
  temporary <- tempfile()
  GET(full_url, write_disk(temporary, overwrite = TRUE))
  
  RTM_data <- unzip(temporary, exdir = tempdir()) |>
    read_csv()

  full_RTM_data <- rbind(full_RTM_data, RTM_data)
  Sys.sleep(5)
  
}

write.csv(full_RTM_data, paste0(here(), "/2024_Energy_Price/RTM.csv"))

```

```{r}
dates <- seq.Date(as.Date("2024-01-01"), as.Date("2025-01-01"), by = "month")
dates <- format(dates, "%Y%m%d")

first <- "http://oasis.caiso.com/oasisapi/SingleZip?resultformat=6&queryname=PRC_LMP&version=12&startdatetime="
full_DAM_data <- data.frame()

for (date in 1:(length(dates) - 1)) {
  full_url <- paste0(first, dates[date], "T08:00-0000")
  full_url <- paste0(full_url, "&enddatetime=", dates[date + 1], "T07:00-0000&market_run_id=DAM&node=DLAP_PGAE-APND,DLAP_SCE-APND,DLAP_SDGE-APND,DLAP_VEA-APND")
  
  
  temporary <- tempfile()
  GET(full_url, write_disk(temporary, overwrite = TRUE))
  
  DAM_data <- unzip(temporary, exdir = tempdir()) |>
    read_csv()

  full_DAM_data <- rbind(full_DAM_data, DAM_data)
  Sys.sleep(5)
  
}

write.csv(full_DAM_data, paste0(here(), "/2024_Energy_Price/DAM.csv"))
```

```{r}
print(full_url)
```

```{r}
print("http://oasis.caiso.com/oasisapi/SingleZip?resultformat=6&queryname=PRC_LMP&version=12&startdatetime=20250301T08:00-0000&enddatetime=20250401T07:00-0000&market_run_id=DAM&node=DLAP_PGAE-APND,DLAP_SCE-APND,DLAP_SDGE-APND,DLAP_VEA-APND")
```

```{r}
temporary <- tempfile()
GET("https://api.eia.gov/v2/electricity/rto/region-data/data/?frequency=hourly&data[0]=value&start=2024-01-01T00&end=2025-01-01T00&sort[0][column]=period&sort[0][direction]=desc&offset=0&length=5000&api_key=xaEEOWahgBap04j3Eux2kEhkYL0ia3uLrfkbolMN", write_disk(temporary, overwrite = TRUE))
data <- temporary |>
  read_table()
write.csv(data, paste0(here(), "/2024_Energy_Price/hourlyDemand.csv"))
```
